version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily" # Check for updates daily
    ignore:
      - dependency-name: "@types/bcrypt"
      - dependency-name: "@types/body-parser"
      - dependency-name: "@types/cookie-parser"
      - dependency-name: "@types/cors"
      - dependency-name: "@types/ejs"
      - dependency-name: "@types/express"
      - dependency-name: "@types/jest"
      - dependency-name: "@types/jsonwebtoken"
      - dependency-name: "@types/multer"
      - dependency-name: "@types/node"
      - dependency-name: "jest"
      - dependency-name: "mongodb-memory-server"
      - dependency-name: "ncp"
      - dependency-name: "nodemon"
      - dependency-name: "ts-jest"
      - dependency-name: "ts-node"
      - dependency-name: "typescript"
