# This is just example data!
version: '3'
services:
  athletpt:
    image: yourImageName:latest
    ports:
      - '8080:8080'
    environment:
      - MONGODB_URI=mongodb://yourMongoUser:yourMongoPassword@mongodb:27017
      - PORT=8080
      - TOKEN_SECRET=yourTokenSecret
      - DB_NAME=yourDBName
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=yourRedisPassword
      - ENV=dev
    networks:
      - internal_network
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yourMongoUser
      - MONGO_INITDB_ROOT_PASSWORD=yourMongoPassword
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal_network

  redis:
    image: redis:latest
    command: redis-server --requirepass yourRedisPassword
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - internal_network

networks:
  internal_network:

volumes:
  mongodb_data:
  redis_data: